#ifndef _MMU_H
#define _MMU_H

#include "arm/sysregs.h"

#define MM_TYPE_PAGE_TABLE 0x3
#define MM_TYPE_PAGE 0x3
#define MM_TYPE_BLOCK 0x1
#define MM_ACCESS (0x1 << 10)
#define MM_ACCESS_PERMISSION (0x01 << 6)

#define MMU_FLAGS (MM_TYPE_BLOCK | (MT_NORMAL_NC << 2) | MM_ACCESS)
#define MMU_DEVICE_FLAGS (MM_TYPE_BLOCK | (MT_DEVICE_nGnRnE << 2) | MM_ACCESS)
#define MMU_PTE_FLAGS (MM_TYPE_PAGE | (MT_NORMAL_NC << 2) | MM_ACCESS | MM_ACCESS_PERMISSION)

#define ENTRY_TYPE_TABLE_DESCRIPTOR 0x11
#define ENTRY_TYPE_BLOCK_ENTRY 0x01
#define ENTRY_TYPE_TABLE_ENTRY 0x11
#define ENTRY_TYPE_INVALID 0x00

#define MM_DESCRIPTOR_VALID (0x1)
#define MM_DESCRIPTOR_BLOCK (0x0 << 1)
#define MM_DESCRIPTOR_TABLE (0x1 << 1)

// Block attributes
#define MM_DESCRIPTOR_EXECUTE_NEVER (0x1ull << 54)
#define MM_DESCRIPTOR_CONTIGUOUS    (0x1ull << 52)
#define MM_DESCRIPTOR_ACCESS_FLAG   (0x1ull << 10)

#define MM_DESCRIPTOR_NON_SHAREABLE (0x00ull << 8)
#define MM_DESCRIPTOR_OUTER_SHAREABLE (0x10ull << 8)
#define MM_DESCRIPTOR_INNER_SHAREABLE (0x11ull << 8)

#define MM_DESCRIPTOR_MAIR_INDEX(index) (index << 2)

#define MM_TTBR_CNP (0x1)

#endif /* _MMU_H */
