name: Archive Source Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Create archive
      run: zip -r source_code.zip .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: source-code
        path: source_code.zip