name: Generate Doxygen

on:
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Doxygen
      run: sudo apt-get install doxygen graphviz -y

    - name: Generate Doxygen documentation
      run: doxygen Doxyfile

    - name: Upload Doxygen documentation
      uses: actions/upload-artifact@v4
      with:
        name: doxygen-docs
        path: docs/doxygen/html
