on:
  push:
    branches:
    - main

jobs:
  build:
    name: build job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          submodules: true

      - name: Fetch aarch64-none-elf toolchain
        run: |
          wget https://developer.arm.com/-/media/Files/downloads/gnu/13.3.rel1/binrel/arm-gnu-toolchain-13.3.rel1-x86_64-aarch64-none-elf.tar.xz
          tar -xf arm-gnu-toolchain-13.3.rel1-x86_64-aarch64-none-elf.tar.xz
          sudo mv arm-gnu-toolchain-13.3.rel1-x86_64-aarch64-none-elf /opt/
          echo "/opt/arm-gnu-toolchain-13.3.rel1-x86_64-aarch64-none-elf/bin" >> "$GITHUB_PATH"

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y xmake

      - name: Run xmake
        run: xmake

      - name: Upload kernel8.elf
        uses: actions/upload-artifact@v4.4.3
        with:
          name: kernel8.elf
          path: kernel8.elf
