on:
  push:
    branches:
    - main

jobs:
  build:
    name: build job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          submodules: true

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y llvm python3 ninja-build lld

      - name: Generate ninja.build
        run: python3 conf.py

      - name: Run ninja
        run: ninja

      - name: Upload kernel8.img
        uses: actions/upload-artifact@v4.4.3
        with:
          name: kernel8.img
          path: kernel8.img

      - name: Upload kernel8.elf
        uses: actions/upload-artifact@v4.4.3
        with:
          name: kernel8.elf
          path: kernel8.elf
